name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt

      - uses: actions/checkout@v5
      - name: Generate Verilog for bytebeat_the42melody
        uses: ./.github/actions/xls-action
        with:
          xls-version: v0.0.0-8961-gf509bf088
          dslx-path: src/bytebeat_the42melody.x
          dslx-top: bytebeat_the42melody
          ir-path: src/bytebeat_the42melody.ir
          opt-ir-path: src/bytebeat_the42melody.opt.ir
          verilog-path: src/bytebeat_the42melody.v
          verilog-module-name: bytebeat_the42melody
          verilog-reset-signal-name: reset
          use-system-verilog: false
          clock-period-ps: 488281
          delay-model: sky130
          artifact-name: xls-generated-the42melody
      - name: Generate Verilog for bytebeat_sierpinskiharmony
        uses: ./.github/actions/xls-action
        with:
          xls-version: v0.0.0-8961-gf509bf088
          dslx-path: src/bytebeat_sierpinskiharmony.x
          dslx-top: bytebeat_sierpinskiharmony
          ir-path: src/bytebeat_sierpinskiharmony.ir
          opt-ir-path: src/bytebeat_sierpinskiharmony.opt.ir
          verilog-path: src/bytebeat_sierpinskiharmony.v
          verilog-module-name: bytebeat_sierpinskiharmony
          verilog-reset-signal-name: reset
          use-system-verilog: false
          clock-period-ps: 488281
          delay-model: sky130
          artifact-name: xls-generated-sierpinskiharmony
      - name: Generate Verilog for bytebeat_fractaltrees
        uses: ./.github/actions/xls-action
        with:
          xls-version: v0.0.0-8961-gf509bf088
          dslx-path: src/bytebeat_fractaltrees.x
          dslx-top: bytebeat_fractaltrees
          ir-path: src/bytebeat_fractaltrees.ir
          opt-ir-path: src/bytebeat_fractaltrees.opt.ir
          verilog-path: src/bytebeat_fractaltrees.v
          verilog-module-name: bytebeat_fractaltrees
          verilog-reset-signal-name: reset
          use-system-verilog: false
          clock-period-ps: 488281
          delay-model: sky130
          artifact-name: xls-generated-fractaltrees

      - name: Run tests
        run: |
          cd test
          make clean
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: upload vcd
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/tb.vcd
            test/results.xml
            test/output/*
